
USE products;
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (1,'The Smartwatch 2000 is the perfect companion for your active lifestyle.','https://www.publicdomainpictures.net/pictures/170000/velka/watch-1462898771eM0.jpg','Smartwatch 2000',149.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (2,'Create delicious smoothies and soups with the powerful Deluxe Blender.','https://www.industriemuseum.be/files/attachments/.9567/w1440q85_mixer.jpg','Deluxe Blender',79.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (3,'Play games without interruption with the High-Speed Router.','https://c1.peakpx.com/wallpaper/30/108/932/computer-mouse-hardware-computer-wallpaper.jpg','Gaming Mouse',69.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (5,'Enjoy high-quality sound and voice-controlled convenience with the Smart Speaker.','https://images.pexels.com/photos/4893862/pexels-photo-4893862.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200','Smart Speaker',110.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (6,'Turn any room into a movie theater with the Portable Projector.','https://media.sketchfab.com/models/0b107065c28f4972a72d5053d3f24591/thumbnails/52ecf9e699ea454ebd6d008b88ad1c52/aff8eca4313f4875ba2cc05e354fe839.jpeg','Portable Projector',249.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (1,'Track your workouts and monitor your health with the Fitness Tracker.','http://gadgetsin.com/uploads/2019/03/fitbit_inspire_hr_fitness_tracker_with_heart_rate_monitor_2.jpg','Fitness Tracker',99.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (2,'Fry your favorite foods without the oil using the Air Fryer.','https://www.mingguanwanita.my/wp-content/uploads/2018/03/morgan-air-fryer-2-35l-maf-a988-sermin123-1709-07-SERMIN123@18.jpg','Air Fryer',129.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (5,'Enjoy your music wirelessly and in style with the Wireless Earbuds.','http://gadgetsin.com/uploads/2019/08/liberate_air_true_wireless_earbuds_1.jpg','Wireless Earbuds',119.99);
INSERT INTO "product" (cat_id, description, image, name, price)  VALUES (6,'This 4K TV features a large, high-resolution screen with HDR support and smart TV capabilities.','https://gamersocupados.com/wp-content/uploads/2018/05/Televisor-CRT-Antiguo-1024x683.jpg','4K Smart TV',899.99);
